# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81b31f81b6dc96e17ae28fb9ffb944b04c6e6c4773498765567c489f39b5cd6a39621b3394a7a6fef3f0578b2bb70f7a431f14cc8cf368cdd5dca6cd04017ab8

test:
  secret_key_base: ae0e689884b05fd67b0c30882f1d7b9e1c56578211d27bb75c4dff623f903982af9b7062a6d8c7a991698ec179613a3ca9922965b45b613a407fb8d4a094597b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
